# Generated by Django 5.2.7 on 2025-11-18 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_trained', models.BooleanField(default=False)),
                ('last_trained', models.DateTimeField(blank=True, null=True)),
                ('total_records', models.IntegerField(default=0)),
                ('products_analyzed', models.IntegerField(default=0)),
                ('predictions_generated', models.IntegerField(default=0)),
                ('accuracy', models.IntegerField(default=85)),
                ('model_type', models.CharField(default='Linear Regression (Moving Average)', max_length=200)),
                ('training_period_days', models.IntegerField(default=90)),
            ],
            options={
                'db_table': 'ml_models',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('stock', models.FloatField(default=0)),
                ('unit', models.CharField(default='pcs', max_length=50)),
                ('price', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_daily_usage', models.FloatField()),
                ('avg_daily_usage', models.FloatField()),
                ('trend', models.FloatField()),
                ('confidence_score', models.FloatField()),
                ('data_points', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ml_prediction', to='dashboard.product')),
            ],
            options={
                'db_table': 'ml_predictions',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_firebase_id', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('total', models.FloatField(blank=True, null=True)),
                ('order_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='dashboard.product')),
            ],
            options={
                'db_table': 'sales',
                'ordering': ['-order_date'],
            },
        ),
    ]
