# Generated by Django 5.2.7 on 2025-11-19 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_sale_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('product_firebase_id', models.CharField(db_index=True, max_length=100)),
                ('product_number', models.IntegerField(default=0)),
                ('product_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='dashboard.product')),
            ],
            options={
                'db_table': 'recipes',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_firebase_id', models.CharField(db_index=True, max_length=100)),
                ('ingredient_name', models.CharField(max_length=200)),
                ('quantity_needed', models.FloatField()),
                ('unit', models.CharField(default='g', max_length=50)),
                ('recipe_firebase_id', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_in_recipes', to='dashboard.product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='dashboard.recipe')),
            ],
            options={
                'db_table': 'recipe_ingredients',
            },
        ),
    ]
