# Generated by Django 5.2.8 on 2025-11-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_add_dual_inventory_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditTrail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("action", models.CharField(max_length=255)),
                ("details", models.TextField(blank=True, null=True)),
                (
                    "user_id",
                    models.CharField(
                        blank=True, db_column="userId", max_length=255, null=True
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        blank=True, db_column="userName", max_length=255, null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "audit_trail",
                "ordering": ["-timestamp"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="WasteLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "product_firebase_id",
                    models.CharField(db_column="productFirebaseId", max_length=255),
                ),
                (
                    "product_name",
                    models.CharField(db_column="productName", max_length=255),
                ),
                ("quantity", models.FloatField()),
                ("reason", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("waste_date", models.DateTimeField(db_column="wasteDate")),
                (
                    "recorded_by",
                    models.CharField(
                        blank=True, db_column="recordedBy", max_length=255, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="createdAt", null=True
                    ),
                ),
            ],
            options={
                "db_table": "waste_logs",
                "ordering": ["-waste_date"],
                "managed": True,
            },
        ),
        migrations.AlterModelOptions(
            name="mlmodel",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="mlprediction",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="recipe",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="recipeingredient",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="sale",
            options={"managed": False, "ordering": ["-order_date"]},
        ),
        migrations.RemoveField(
            model_name="mlprediction",
            name="product",
        ),
        migrations.AddField(
            model_name="mlprediction",
            name="product_firebase_id",
            field=models.CharField(
                db_column="productFirebaseId", default="", max_length=255, unique=True
            ),
        ),
        migrations.AddField(
            model_name="mlprediction",
            name="product_name",
            field=models.CharField(
                blank=True,
                db_column="productName",
                default="",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="is_trained",
            field=models.BooleanField(db_column="isTrained", default=False),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="last_trained",
            field=models.DateTimeField(blank=True, db_column="lastTrained", null=True),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="model_type",
            field=models.CharField(
                db_column="modelType",
                default="Linear Regression (Moving Average)",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="predictions_generated",
            field=models.IntegerField(db_column="predictionsGenerated", default=0),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="products_analyzed",
            field=models.IntegerField(db_column="productsAnalyzed", default=0),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="total_records",
            field=models.IntegerField(db_column="totalRecords", default=0),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="training_period_days",
            field=models.IntegerField(db_column="trainingPeriodDays", default=90),
        ),
        migrations.AlterField(
            model_name="mlprediction",
            name="avg_daily_usage",
            field=models.FloatField(db_column="avgDailyUsage"),
        ),
        migrations.AlterField(
            model_name="mlprediction",
            name="confidence_score",
            field=models.FloatField(db_column="confidenceScore"),
        ),
        migrations.AlterField(
            model_name="mlprediction",
            name="data_points",
            field=models.IntegerField(db_column="dataPoints"),
        ),
        migrations.AlterField(
            model_name="mlprediction",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="mlprediction",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, db_column="lastUpdated"),
        ),
        migrations.AlterField(
            model_name="mlprediction",
            name="predicted_daily_usage",
            field=models.FloatField(db_column="predictedDailyUsage"),
        ),
    ]
